Part8_Restructure_Dashboard/dashboard/blueprint.py
from flask import Blueprint, render_template, current_app

import pandas as pd
import json
import plotly
import plotly.express as px


dashboard_blueprint = Blueprint('dashboard', __name__,
    template_folder='templates',
    static_folder='static', static_url_path='assets')

@dashboard_blueprint.route('/')
def db_blueprint_dashboard():

    print(current_app.config['loggedin'])

    if current_app.config['loggedin'] == 'false':
        return render_template('login.html')

    else:

        sample_data = pd.DataFrame({
                "Vegetables": ["Lettuce", "Cauliflower", "Carrots", "Lettuce", "Cauliflower", "Carrots"],
                "Amount": [10, 15, 8, 5, 14, 25],
                "City": ["London", "London", "London", "Madrid", "Madrid", "Madrid"]
            })

        fig = px.bar(sample_data, x="Vegetables", y="Amount", color="City", barmode="stack")
        fig2 = px.bar(sample_data, x="City", y="Amount", color="Vegetables", barmode="group")
        
        print('fig: ', fig)
        graphJSON = json.dumps(fig, cls=plotly.utils.PlotlyJSONEncoder)
        graphJSON2 = json.dumps(fig2, cls=plotly.utils.PlotlyJSONEncoder)
        print('graphJSON: ', graphJSON)

        return render_template('dashboard.html', graphJSON=graphJSON, graphJSON2=graphJSON2)

Part8_Restructure_Dashboard/templates/about.html
{% extends 'base.html' %}

{% block title%}About page{% endblock %}

{% block content %}

<h1>About page</h1>

<p>
    This is about page
</p>

{% endblock %}

Part8_Restructure_Dashboard/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <meta charset="UTF-8">
    <title>
            {% block title %} 
            {% endblock %} 
    </title>
</head>
<body>

{% block body %} 

{% endblock %}


<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</body>
</html>

Part8_Restructure_Dashboard/templates/dashboard.html
{% extends 'base.html' %}
{% include 'header.html' %}
{% block title %} Home {% endblock %}
{% block body %}

<div>
    
    <h1> Future dashboard page will go here .....</h1>
    
    <body style="font-family:arial, sans-serif">
        <div id="chart" class="chart"></div>
    </body>

    
    <!-- just need to load this script in once -->
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>

    <!-- for each datapoint/graph, need to assign a ID  -->
    <script type="text/javascript">
        var graphs = {{graphJSON | safe}};
        Plotly.plot('chart', graphs, {});        
    </script>


</div>

{% endblock %}

Part8_Restructure_Dashboard/templates/header.html
{% extends 'base.html' %}

{% block title %} 
    Patient Portal
{% endblock %}



{% block body %}

    <!-- insert bootstrap nav bar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Patient Portal</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link" href="{{ url_for('get_gui_patients') }}">Patient</a>
                    <a class="nav-link" href="{{ url_for('dashboard.db_blueprint_dashboard') }}">Dashboard</a>
                    <a class="nav-link" href="">Messaging</a>
                    <a class="nav-link" href="">Settings</a>
                    <a class="nav-link" href="{{ url_for('account') }}">Account</a>
                    <a class="nav-link" href="{{ url_for('logout') }}">Logout</a>
                </div>
            </div>
        </div>
    </nav>

    <br />


    <!-- <div class="jumbotron p-3">
        <div class="well text-center">
            <h1>Patient Self Service Portal (PssP - Admin v.02) </h1>
        </div>
    </div> -->

{% endblock %}

Part8_Restructure_Dashboard/templates/image_upload.html
{% extends 'base.html' %}
{% include 'header.html' %}
{% block title %} Home {% endblock %}
{% block body %}

<!-- create a view with four containers, the first container is for demographics,
the second container is for vitals, the third container is for allergies, and the fourth container is for medications -->

<!-- create a bootstrap side navigation bar that is horizontal -->


<!-- create a new container with two columns -->
<div class="container">

    <form method="POST" action="/upload" enctype="multipart/form-data">
        <!-- File Upload-->
        <div class="form-group">
            <label for="inputFile">Please select your user image:</label>
            <input class="form-control-file" type="file" name="inputFile">
        </div>

        <!-- Submit -->        
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>



</div>
    








{% endblock %}

                    

Part8_Restructure_Dashboard/templates/landing.html
<!doctype html>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.101.0">
    <title>Starter Template · Bootstrap v5.2</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/starter-template/">

    

    
<!-- THIS IS THE PART BELOW THAT CAME WITH IT, WE NEED TO UPDATE THE LOCATION -->
<!-- <link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet"> -->
<!-- THIS HERE NOW IS THE CORRECT LOCATION BELOW.... -->
<link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.css') }}"> 


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>

    
    <!-- Custom styles for this template -->
    <!-- IMPORTANT we can then override some of the default settings, and load in a 2nd CSS file -->
    <!-- <link href="starter-template.css" rel="stylesheet"> -->
    <link rel="stylesheet" href="{{ url_for('static', filename='landing.css') }}"> 

  </head>
  <body>
    
<div class="col-lg-8 mx-auto p-4 py-md-5">
  <header class="d-flex align-items-center pb-3 mb-5 border-bottom">
    <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
      <span class="fs-4">Patient Self Service Portal (PssP)</span>
    </a>
  </header>

  <main>
    <h1>Get started with your patient portal now!</h1>
    <p class="fs-5 col-md-8"> Start by either registering a new account, or sign-in to a existing account</p>

    <div class="mb-5">
      <a href="/login" class="btn btn-primary btn-lg px-4">Sign in</a>
      <a href="/register" class="btn btn-primary btn-lg px-4">Register</a>
    </div>

    <hr class="col-3 col-md-2 mb-5">

  </main>
  <footer class="pt-5 my-5 text-muted border-top">
    Created by AHI Program  &middot; &copy; 2022
  </footer>
</div>


    <script src="../assets/dist/js/bootstrap.bundle.min.js"></script>

      
  </body>
</html>

Part8_Restructure_Dashboard/templates/login.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.101.0">
    <title>Signin Template · Bootstrap v5.2</title>
    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/sign-in/">
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.css') }}"> 
<!-- <link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet"> -->

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>

    
    <!-- Custom styles for this template -->
    <!-- <link href="signin.css" rel="stylesheet"> -->
    <link rel="stylesheet" href="{{ url_for('static', filename='signin.css') }}"> 

  </head>
  <body class="text-center">
    
<main class="form-signin w-100 m-auto">

  <form action="{{ url_for('login') }}" method="post">
    <h1 class="h3 mb-3 fw-normal">Login</h1>

    <div class="form-floating" style="padding: .2em">
      <input type="text" class="form-control" id="username" name="username">
      <label for="floatingInput">Username</label>
    </div>

    <div class="form-floating" style="padding: .2em">
      <input type="password" class="form-control" id="password" name="password">
      <label for="floatingPassword">Password</label>
    </div>

    <div class="msg">{{ msg }}</div>

    <br />
    
    <div class="form-group">
      <button class="btn btn-primary" type="submit" value="Login">Login</button>
      <a href="{{ url_for('register') }}" class="btn btn-primary">Register</a>

    </div>


  </form>


</main>
  </body>
</html>

Part8_Restructure_Dashboard/templates/patient_all.html
{% extends 'base.html' %}
{% include 'header.html' %}
{% block title %} Home {% endblock %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col md-12">
            <div class="jumbotron p-3">

                <h2 style="margin-bottom: 1em;"> Patient List
                    <button type="button" class="btn btn-success float-right"
                        data-toggle="modal" data-target="#addpatient">Add New Patient
                    </button> 
                </h2>


                {% with messages = get_flashed_messages() %}
                {% if messages %}
                {% for message in messages %}

                <div class="alert alert-success alert-dismissable" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="close">
                        <span aria-hidden="true">x</span>
                    </button>

                {{message}}

                </div>


                {% endfor %}
                {% endif %}
                {% endwith %}


                <table class="table table-hover table-dark">

                    <tr>

                        <th>ID</th>
                        <th>MRN</th>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Zip Code</th>
                        <th>Gender</th>
                        <th>Setting</th>

                    </tr>


                   {% for row in patients %}
                    <tr>
                        <td>{{row.id}}</td>
                        <td>{{row.mrn}}</td>
                        <td>{{row.first_name}}</td>
                        <td>{{row.last_name}}</td>
                        <td>{{row.zip_code}} </td>
                        <td>{{row.gender}}</td>
                        <td>
                            <a href="/update/{{row.mrn}}" class="btn btn-warning btn-xs" data-toggle="modal" data-target="#modaledit{{row.mrn}}">Edit</a>
                            <a href="/delete/{{row.mrn}}" class="btn btn-danger btn-xs" onclick="return confirm('Are You Sure To Delete ?')">Delete</a>
                            <a href="/details/{{row.mrn}}" class="btn btn-info btn-xs">Details</a>
                        </td>

                    </tr>


                  <!-- Modal Edit Employee-->


                  
                    <div id="modaledit{{row.mrn}}" class="modal fade" role="dialog">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h4 class="modal-title">Update Information</h4>
                            </div>
                            <div class="modal-body">
                                <form action="{{url_for('update')}}" method="POST">
                                <div class="form-group">
                                    <label for="mrn">MRN</label>
                                    <input type="text" class="form-control" name="mrn" value="{{row.mrn}}" readonly>
                                </div>
                                <div class="form-group">
                                    <label>First name:</label>
                                    <input type="text" class="form-control" name="first_name" value="{{row.first_name}}">
                                </div>
                                <div class="form-group">
                                    <label>Last name:</label>
                                    <input type="text" class="form-control" name="last_name" value="{{row.last_name}}">
                                </div>
                                <div class="form-group">
                                    <label>Gender:</label>
                                    <input type="text" class="form-control" name="gender" value="{{row.gender}}">
                                </div> 
                                <div class="form-group">
                                    <button class="btn btn-primary" type="submit">Update</button>
                                </div>
                                </form>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                    </div>


                    {% endfor %}


                </table>


            </div>



                  <!-- Modal Add Patient-->


        <div id="addpatient" class="modal fade" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">Add Patient</h4>
                    </div>
                    <div class="modal-body">

                        <form action="{{url_for('insert')}}" method="POST">
                            <div class="form-group">
                                <label>Medical Record Number:</label>
                                <input type="text" class="form-control" name="mrn" required="1">
                            </div>
                            <div class="form-group">
                                <label>First Name:</label>
                                <input type="text" class="form-control" name="first_name" required="1">
                            </div>
                            <div class="form-group">
                                <label>Last Name:</label>
                                <input type="text" class="form-control" name="last_name" required="1">
                            </div>
                            <div class="form-group">
                                <label>Zip Code </label>
                                <input type="text" class="form-control" name="zip_code" required="1">
                            </div>
                            <div class="form-group">
                                <label> Gender </label>
                                <input type="text" class="form-control" name="gender" required="1">
                            </div>
                            <div class="form-group">
                                <button class="btn btn-primary" type="submit">Add Patient</button>
                            </div>
                        </form>

                    </div>


                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>





        </div>
    </div>
</div>


{% endblock %}

Part8_Restructure_Dashboard/templates/register.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.101.0">
    <title>Signin Template · Bootstrap v5.2</title>
    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/sign-in/">
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.css') }}"> 
<!-- <link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet"> -->

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>

    
    <!-- Custom styles for this template -->
    <!-- <link href="signin.css" rel="stylesheet"> -->
    <link rel="stylesheet" href="{{ url_for('static', filename='signin.css') }}"> 

  </head>
  <body class="text-center">
    
<main class="form-signin w-100 m-auto">

  <form action="{{ url_for('register') }}" method="post">
    <h1 class="h3 mb-3 fw-normal">Register Account</h1>

    <!-- create new input with drop down selection for account type -->
    <div class="form-floating">
      <select class="form-select" id="account_type" name="account_type">
        <option value="admin">Admin</option>
        <option value="patient">Patient</option>
      </select>
      <label for="floatingSelect">User Type</label>
    </div>

    <br />


    <br />
    
    <div class="form-group">
      <button class="btn btn-primary" type="submit" value="Next">Next</button>
    </div>


  </form>




</main>
  </body>
</html>

Part8_Restructure_Dashboard/templates/register_admin.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.101.0">
    <title>Signin Template · Bootstrap v5.2</title>
    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/sign-in/">
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.css') }}"> 
<!-- <link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet"> -->

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>

    
    <!-- Custom styles for this template -->
    <!-- <link href="signin.css" rel="stylesheet"> -->
    <link rel="stylesheet" href="{{ url_for('static', filename='signin.css') }}"> 

  </head>
  <body class="text-center">
    
<main class="form-signin w-100 m-auto">

  <form action="{{ url_for('register_admin') }}" method="post">
    <h1 class="h3 mb-3 fw-normal">Admin Account</h1>


    <div class="form-floating" style="padding: .2em">
      <input type="email" class="form-control" id="email" name="email" required>
      <label for="floatingInput">Email</label>
    </div>

    <div class="form-floating" style="padding: .2em">
      <input type="text" class="form-control" id="username" name="username" required>
      <label for="floatingInput">Username</label>
    </div>

    <div class="form-floating" style="padding: .2em">
      <input type="password" class="form-control" id="password" name="password" required>
      <label for="floatingPassword">Password</label>
    </div>

    <div class="msg">{{ msg }}</div>

    <br />
    
    <div class="form-group">
      <button class="btn btn-primary" type="submit" value="Register">Create Admin Account</button>
      <!-- <a href="{{ url_for('login') }}" class="btn btn-primary">Login</a> -->

    </div>


  </form>




</main>
  </body>
</html>

Part8_Restructure_Dashboard/templates/register_patient.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.101.0">
    <title>Signin Template · Bootstrap v5.2</title>
    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/sign-in/">
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.css') }}"> 
<!-- <link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet"> -->

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>

    
    <!-- Custom styles for this template -->
    <!-- <link href="signin.css" rel="stylesheet"> -->
    <link rel="stylesheet" href="{{ url_for('static', filename='signin.css') }}"> 

  </head>
  <body class="text-center">
    
<main class="form-signin w-100 m-auto">

  <form action="{{ url_for('register_patient') }}" method="post">


    <h1 class="h3 mb-3 fw-normal">Patient Account</h1>

    <!-- first name -->
    <div class="form-floating" style="padding: .2em">
        <input type="text" class="form-control" id="first_name" name="first_name" required>
        <label for="floatingInput">First Name</label>
    </div>

    <!-- last name -->
    <div class="form-floating" style="padding: .2em">
        <input type="text" class="form-control" id="last_name" name="last_name" required>
        <label for="floatingInput">Last Name</label>
    </div>

    <!-- zip code -->
    <div class="form-floating" style="padding: .2em">
        <input type="text" class="form-control" id="zip_code" name="zip_code" required>
        <label for="floatingInput">Zip Code</label>
    </div>

    <!-- bootstrap calendar selector for date of birth -->
    <div class="form-floating" style="padding: .2em">
        <input type="date" class="form-control" id="dob" name="dob" required>
        <label for="floatingInput">Date of Birth</label>
    </div>

    <!-- create single select for sex -->
    <div class="form-floating">
        <select class="form-select" id="gender" name="gender">
          <option value="male">Male</option>
          <option value="female">Female</option>
          <option value="other">Other</option>
        </select>
        <label for="floatingSelect">User Type</label>
    </div>


    <!-- create a drop down of conditions that is multi-select for the patient to choose between -->
    <!-- this brings in the conditions object and loops through -->
    <label for="floatingSelect" style="margin-bottom: 0; margin-top: 1em">Conditions</label>
    <div class="form-floating" style="padding-top: 1em; padding-bottom:1em">
        <select class="form-select" 
        id="conditions" name="conditions" multiple aria-label="multiple select example" style="font-size: large; width: auto; height: auto;" >
          {% for condition in conditions %}
            <option value="{{ condition.icd10_code }}">{{ condition.icd10_description }}</option>
          {% endfor %}
        </select>
    </div>





    <!-- mobile phone  -->
    <div class="form-floating" style="padding: .2em">
        <input type="text" class="form-control" id="contact_mobile" name="contact_mobile" required>
        <label for="floatingInput">Phone Number (mobile) </label>
    </div>

    <!-- home phone -->
    <div class="form-floating" style="padding: .2em">
        <input type="text" class="form-control" id="contact_home" name="contact_home" required>
        <label for="floatingInput">Phone Number (mobile) </label>
    </div> 

    <!-- email -->
    <div class="form-floating" style="padding: .2em">
      <input type="email" class="form-control" id="email" name="email" required>
      <label for="floatingInput">Email</label>
    </div>

    <!-- username -->
    <div class="form-floating" style="padding: .2em">
        <input type="text" class="form-control" id="username" name="username" required>
      <label for="floatingInput">Username</label>
    </div>

    <!-- password -->
    <div class="form-floating" style="padding: .2em">
        <input type="password" class="form-control" id="password" name="password" required>
      <label for="floatingPassword">Password</label>
    </div>

    <div class="msg">{{ msg }}</div>

    <br />
    
    <div class="form-group">
      <button class="btn btn-primary" type="submit" value="Register">Create Patient Account</button>

    </div>


  </form>




</main>
  </body>
</html>